[Autograd] Improve error for leaf tensors as out argument to fallback
Currently operators that hit the autograd fallback call `check_inplace`
on all mutated inputs, including out arguments. This leads to a slightly
confusing error message:
```python
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```

Compared to functions that don't fallback, which raise
```python
RuntimeError: add(): functions with out=... arguments don't support automatic differentiation, but one of the arguments requires grad.
``

This changes the error message to make clear the issue is with the out argument,
but does not tighten the check to outright ban out arguments that require grad.
Instead, I use the same checks from `check_inplace` which allows non-leaf tensors
that require grad to pass without error.

ghstack-source-id: 37ca63627a2a76b6ec951c511912deb0823908bf
Pull Request resolved: https://github.com/pytorch/pytorch/pull/121089